# Generated by Django 2.0.1 on 2018-01-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workatolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='up_category',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs_set', to='workatolist.Category'),
        ),
    ]
